name: Flutter CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.0'

      - name: Change directory to Flutter app
        run: cd safran

      - name: Install dependencies
        run: flutter pub get
        working-directory: safran

      - name: Analyze Dart code
        run: flutter analyze
        working-directory: safran

      - name: Run tests with coverage
        run: flutter test --coverage
        working-directory: safran

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage/lcov.info
          flags: flutter
          name: flutter-app
          fail_ci_if_error: true
