name: Deploy Flutter App

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-notify:
    name: Build and Notify
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3'

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install dependencies
        run: flutter pub get
        working-directory: safran

      - name: Build APK
        run: flutter build apk --release
        working-directory: safran

      - name: Build App Bundle
        run: flutter build appbundle
        working-directory: safran

      - name: Generate Changelog
        id: changelog
        run: |
          echo "CHANGELOG<<EOF" >> $GITHUB_ENV
          git log -1 --pretty=format:"%h - %s (%an)" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Upload APK artifact
        uses: actions/upload-artifact@v3
        with:
          name: flutter-apk
          path: safran/build/app/outputs/flutter-apk/app-release.apk

      - name: Upload AAB artifact
        uses: actions/upload-artifact@v3
        with:
          name: flutter-aab
          path: safran/build/app/outputs/bundle/release/app-release.aab

      - name: Notify on Discord
        if: success()
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d '{"content": "**Nouvelle version buildée : `${{ github.ref_name }}`**\n📝 *Changelog :* ${{ env.CHANGELOG }}"}' \
               ${{ secrets.DISCORD_WEBHOOK }}
